baseURL = "http://taiseimachiya.github.io"
languageCode = "ja"
title = "My Blog Site"
contentDir = "post"
disableKinds = ["RSS","sitemap"]
theme = "ananke"
publishDir = "docs"
[taxonomies]
tag = "tags"

